[MFLOG|0|2025-04-21T22:04:24.580199Z|runtime|72574df1-c74b-4330-9dc0-4754de209732]<flow ClassifierTrainFlow step choose_model> failed:
[MFLOG|0|2025-04-21T22:04:24.585726Z|runtime|78a28bfb-f92c-439e-bc14-d06307b2b548]    Internal error
[MFLOG|0|2025-04-21T22:04:24.587715Z|runtime|eea75c2d-fb24-4a93-ad90-81d30bdcdb08]Traceback (most recent call last):
[MFLOG|0|2025-04-21T22:04:24.587917Z|runtime|491c5ed3-e742-4168-aa79-e572ead90bda]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli.py", line 619, in main
[MFLOG|0|2025-04-21T22:04:24.588001Z|runtime|4def500e-b4bf-4e5d-abc6-2aea75a615cd]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2025-04-21T22:04:24.588056Z|runtime|94ece48d-3fc2-425f-865e-51e045ad5e8b]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2025-04-21T22:04:24.588123Z|runtime|cca152b0-f1a3-4e5b-8974-645a6c1afe04]    return self.main(args, kwargs)
[MFLOG|0|2025-04-21T22:04:24.588173Z|runtime|34b56010-7648-4b5e-a10e-603fdb18f331]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.588286Z|runtime|8337dfa2-ba37-420b-9679-d32dc57fd046]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2025-04-21T22:04:24.588331Z|runtime|bd9dfe4c-9c7d-4ad8-8465-0cf588eb29db]    rv = self.invoke(ctx)
[MFLOG|0|2025-04-21T22:04:24.588376Z|runtime|db6ae0d6-9a01-457a-8137-5269f9e2855f]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.588424Z|runtime|05bb83fa-e6f5-4548-ae62-fc966d5d6ea9]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/utils.py", line 69, in invoke
[MFLOG|0|2025-04-21T22:04:24.588464Z|runtime|01436b53-ced9-45d8-aebc-8498cbe8d706]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2025-04-21T22:04:24.588503Z|runtime|8e38a0fc-6ad2-4173-a4d3-8d77abf8c478]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.588554Z|runtime|71e8a19b-6849-4c27-b5ef-e0446bc50f5e]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2025-04-21T22:04:24.588593Z|runtime|ca00dac7-daa9-4fe6-8bfc-1e9554c48db1]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2025-04-21T22:04:24.588632Z|runtime|7401e0fd-6fda-48a6-8937-23922c60dc5f]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.588672Z|runtime|14b2cb48-5349-4573-9db4-29ebf6fd3a37]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2025-04-21T22:04:24.588714Z|runtime|f5bb01f0-9558-4ace-b8e3-7628efbff227]    return callback(args, kwargs)
[MFLOG|0|2025-04-21T22:04:24.724460Z|runtime|2dd63eac-b335-44ce-bd77-b2a30430933e]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.724631Z|runtime|da81a777-c211-4c70-8ec1-87ca76948b31]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2025-04-21T22:04:24.724669Z|runtime|efe78c81-de2d-4d3f-8da2-dff18a61079b]    return func(args, kwargs)
[MFLOG|0|2025-04-21T22:04:24.724694Z|runtime|23525788-8e9d-424e-b855-00667bbd39cd]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.724721Z|runtime|231c1fdc-7542-44cc-9c3e-cfa031392853]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2025-04-21T22:04:24.724743Z|runtime|1c88c65b-9f17-4c01-b800-c1e96a935e7f]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2025-04-21T22:04:24.724765Z|runtime|c63b41f1-075d-4f96-aee5-e65f89caed32]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.724789Z|runtime|19aa7e4a-1701-494f-b0e2-d893cb04cd8f]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/step_cmd.py", line 167, in step
[MFLOG|0|2025-04-21T22:04:24.724813Z|runtime|df2bfcca-a04b-4c14-888b-648e594a8cd5]    task.run_step(
[MFLOG|0|2025-04-21T22:04:24.724840Z|runtime|56626626-7e09-47d6-a36b-251f55b1dcd0]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 670, in run_step
[MFLOG|0|2025-04-21T22:04:24.724862Z|runtime|d1608883-f021-408f-b06f-27a1c90f2fba]    self._exec_step_function(step_func, input_obj)
[MFLOG|0|2025-04-21T22:04:24.724884Z|runtime|1cab8297-579d-4023-a00e-0050a86f932b]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 64, in _exec_step_function
[MFLOG|0|2025-04-21T22:04:24.724910Z|runtime|9c32ddbd-566e-4e2f-8dd0-c85a4bc62a23]    step_function(input_obj)
[MFLOG|0|2025-04-21T22:04:24.724936Z|runtime|96ef043a-fc89-4cb1-b764-a46180adedb5]  File "/Users/poojabaraluumesh/MSDS/spring_2/mlops/labs/lab6/classifier_train.py", line 34, in choose_model
[MFLOG|0|2025-04-21T22:04:24.724958Z|runtime|57ac6caa-00f8-4c41-bf01-2ec682f3b7df]    mlflow.set_experiment('metaflow-experiment')
[MFLOG|0|2025-04-21T22:04:24.724979Z|runtime|bd7a8fdd-9ad2-414a-94ed-2846e3292412]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 143, in set_experiment
[MFLOG|0|2025-04-21T22:04:24.725000Z|runtime|70b8a4c1-fd41-4bf6-b9e9-8ab33da72288]    experiment = client.get_experiment_by_name(experiment_name)
[MFLOG|0|2025-04-21T22:04:24.725021Z|runtime|43234a93-b23b-4586-9124-a08a6f145107]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.725045Z|runtime|108bbca4-2e59-44d0-9998-2e756cb5e3ed]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/tracking/client.py", line 1240, in get_experiment_by_name
[MFLOG|0|2025-04-21T22:04:24.725065Z|runtime|99baa34d-b796-4bcb-9d2a-bc0c90b16966]    return self._tracking_client.get_experiment_by_name(name)
[MFLOG|0|2025-04-21T22:04:24.725085Z|runtime|d66a0583-553f-441f-bf32-014c6c57b620]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.725107Z|runtime|77fc3c73-17cf-4827-ae6d-c0c459552f44]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 484, in get_experiment_by_name
[MFLOG|0|2025-04-21T22:04:24.725128Z|runtime|f5afca98-ddea-4a74-bc71-407c24565ea6]    return self.store.get_experiment_by_name(name)
[MFLOG|0|2025-04-21T22:04:24.725148Z|runtime|34889268-5a88-4244-839b-6c827fc28ebc]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.725174Z|runtime|af901935-f20d-40f1-baa9-861196d44707]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 518, in get_experiment_by_name
[MFLOG|0|2025-04-21T22:04:24.725198Z|runtime|8f1ada72-96c9-4c5f-979d-6d8bd2515b68]    response_proto = self._call_endpoint(GetExperimentByName, req_body)
[MFLOG|0|2025-04-21T22:04:24.725218Z|runtime|7b7543f9-d3c6-4e87-8dd2-0b99071aa40d]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.725242Z|runtime|5adebb9e-f246-433c-8d2a-a7ac7359f078]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 81, in _call_endpoint
[MFLOG|0|2025-04-21T22:04:24.725263Z|runtime|b6c13244-08d6-44f4-a225-f03d7ce73b84]    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
[MFLOG|0|2025-04-21T22:04:24.725283Z|runtime|19cdcf92-441a-40c2-b888-df8aceb696b5]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.725311Z|runtime|42bf5fe9-aa35-4548-86a8-efe27c0e5780]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 362, in call_endpoint
[MFLOG|0|2025-04-21T22:04:24.725333Z|runtime|db141341-62d2-4803-89df-cc735bb86687]    response = verify_rest_response(response, endpoint)
[MFLOG|0|2025-04-21T22:04:24.725354Z|runtime|dd1c0721-01b9-44e5-a603-5b859b700649]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T22:04:24.725377Z|runtime|a7fd64fe-18f7-4340-b201-2d931f619348]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 238, in verify_rest_response
[MFLOG|0|2025-04-21T22:04:24.725397Z|runtime|028f2ee7-3b09-4fce-b4c4-5bd13544f457]    raise MlflowException(
[MFLOG|0|2025-04-21T22:04:24.725425Z|runtime|aceb71b3-e0a4-44e1-9c3f-9a801948c465]mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/get-by-name failed with error code 404 != 200. Response body: '
[MFLOG|0|2025-04-21T22:04:24.725446Z|runtime|60b9bbf4-bf80-4c23-9e31-f041eee5ac3d]<html><head>
[MFLOG|0|2025-04-21T22:04:24.725467Z|runtime|822ff9e4-2265-43c7-9753-e7746eeeb1d7]<meta http-equiv="content-type" content="text/html;charset=utf-8">
[MFLOG|0|2025-04-21T22:04:24.725489Z|runtime|650c36e5-a7ad-44d3-a90f-5f9c553bd51c]<title>404 Page not found</title>
[MFLOG|0|2025-04-21T22:04:24.725511Z|runtime|de07b580-f93a-43b9-9a4d-05d92a10df04]</head>
[MFLOG|0|2025-04-21T22:04:24.725532Z|runtime|27626642-be19-4a25-88ed-47ca2f690a71]<body text=#000000 bgcolor=#ffffff>
[MFLOG|0|2025-04-21T22:04:24.725553Z|runtime|960cc9ec-13da-44a7-b8f8-8706761724b7]<h1>Error: Page not found</h1>
[MFLOG|0|2025-04-21T22:04:24.725575Z|runtime|06553922-db97-4ef8-85b1-55a73d4fd2f4]<h2>The requested URL was not found on this server.</h2>
[MFLOG|0|2025-04-21T22:04:24.725606Z|runtime|451f3b7a-56eb-4475-92b8-92884849ba9e]<h2></h2>
[MFLOG|0|2025-04-21T22:04:24.725650Z|runtime|86fff4cb-c1bb-410e-88e7-2831dc1f72b4]</body></html>
[MFLOG|0|2025-04-21T22:04:24.725671Z|runtime|28cd4aee-8731-445f-94c6-16c866ff3544]'
[MFLOG|0|2025-04-21T22:04:24.725693Z|runtime|04671583-a943-41f7-bd4a-6d088a6377e5]
[MFLOG|0|2025-04-21T22:04:24.726151Z|runtime|76fdbdea-fb20-4392-9c80-0b9c99a6a036]Task failed.