[MFLOG|0|2025-04-21T02:20:24.818872Z|runtime|6d54b389-ba9e-4428-a0e9-d35debd88914]
[MFLOG|0|2025-04-21T02:20:25.001398Z|runtime|cb7333c6-4910-48bd-a0ce-b43fe127c7e5]A module that was compiled using NumPy 1.x cannot be run in
[MFLOG|0|2025-04-21T02:20:25.001513Z|runtime|71fa25e4-71ad-488a-b143-3ee071f55767]NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
[MFLOG|0|2025-04-21T02:20:25.001551Z|runtime|c0648429-b6fa-450c-858a-27ac650cbb35]versions of NumPy, modules must be compiled with NumPy 2.0.
[MFLOG|0|2025-04-21T02:20:25.001580Z|runtime|13403546-7b84-4791-a7d0-91b060082c3b]Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
[MFLOG|0|2025-04-21T02:20:25.001609Z|runtime|2a180561-e1f0-4c00-b563-588559f12ba0]
[MFLOG|0|2025-04-21T02:20:25.001656Z|runtime|93163511-05cc-4702-96d3-420e3202e130]If you are a user of the module, the easiest solution will be to
[MFLOG|0|2025-04-21T02:20:25.001689Z|runtime|bdb5b1d4-9edb-47dd-ae53-5016d7eac357]downgrade to 'numpy<2' or try to upgrade the affected module.
[MFLOG|0|2025-04-21T02:20:25.001715Z|runtime|6b591215-e5e1-4209-9bef-28d25aa74c54]We expect that some modules will need time to support NumPy 2.
[MFLOG|0|2025-04-21T02:20:25.001740Z|runtime|dbeb69d8-0ca4-4f18-b6b3-3af6e06e7932]
[MFLOG|0|2025-04-21T02:20:25.001767Z|runtime|2ebe96a3-6154-42ec-a187-4eb5e3048b23]Traceback (most recent call last):  File "/Users/poojabaraluumesh/MSDS/spring_2/mlops/labs/lab6/classifier_train.py", line 54, in <module>
[MFLOG|0|2025-04-21T02:20:25.001796Z|runtime|36791016-f390-4ade-961e-b70c02143522]    ClassifierTrainFlow()
[MFLOG|0|2025-04-21T02:20:25.001820Z|runtime|372d1777-ecdd-486f-8eb1-592f94c1c1a3]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/flowspec.py", line 191, in __init__
[MFLOG|0|2025-04-21T02:20:25.001843Z|runtime|451d94d6-dd78-4c01-8c33-d152b916e684]    cli.main(self)
[MFLOG|0|2025-04-21T02:20:25.001864Z|runtime|642d2e5c-a5fa-425e-abd2-de3d8d736630]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli.py", line 619, in main
[MFLOG|0|2025-04-21T02:20:25.001887Z|runtime|83e62761-7d65-4f9c-8934-30b3fc60e01f]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2025-04-21T02:20:25.001909Z|runtime|e967e68f-542b-4c53-bc90-425d784c3660]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2025-04-21T02:20:25.001935Z|runtime|5bf48361-7e3d-4cf7-8ed3-a1f9e66d2ed3]    return self.main(*args, **kwargs)
[MFLOG|0|2025-04-21T02:20:25.001960Z|runtime|c78f4d68-ff5e-4127-b015-236dbb6640d4]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2025-04-21T02:20:25.001987Z|runtime|8f79070b-b657-46f0-92b8-2df2143daf7a]    rv = self.invoke(ctx)
[MFLOG|0|2025-04-21T02:20:25.002014Z|runtime|bdef3e49-1b6a-4128-a8d5-c65fba7a2517]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/utils.py", line 69, in invoke
[MFLOG|0|2025-04-21T02:20:25.002038Z|runtime|bd9e1441-d61d-467e-80d3-11b31afe61a5]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2025-04-21T02:20:25.002060Z|runtime|eb51e423-62f0-460f-874e-144fe75068db]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2025-04-21T02:20:25.002083Z|runtime|1a95d12b-ecf1-40a3-a898-da12729ccc7b]    return ctx.invoke(self.callback, **ctx.params)
[MFLOG|0|2025-04-21T02:20:25.002107Z|runtime|06deb990-8b67-4394-bb2c-a7f347aa9852]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2025-04-21T02:20:25.002133Z|runtime|dc3f7fe5-aa43-41cb-97ad-150a6108e02b]    return callback(*args, **kwargs)
[MFLOG|0|2025-04-21T02:20:25.002171Z|runtime|46238b7b-14de-4739-9c81-01b9cf829ef2]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2025-04-21T02:20:25.002192Z|runtime|34c7ebb7-533b-4f3b-8dd2-cf8f3afa25c9]    return func(*args, **kwargs)
[MFLOG|0|2025-04-21T02:20:25.002216Z|runtime|3ce56f79-b777-4152-b09c-1cd061c522a0]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2025-04-21T02:20:25.002240Z|runtime|57fe8798-156b-4e85-8a66-5af51a1dd8e4]    return f(get_current_context(), *args, **kwargs)
[MFLOG|0|2025-04-21T02:20:25.002266Z|runtime|fb87b1ac-694e-4a02-8b9f-110839ef34fc]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/step_cmd.py", line 167, in step
[MFLOG|0|2025-04-21T02:20:25.002288Z|runtime|4fa54ad0-72e0-49f5-96ae-6f9844bbcc65]    task.run_step(
[MFLOG|0|2025-04-21T02:20:25.002312Z|runtime|873d8f89-27b9-4cf1-ace5-4941c7b514d1]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 670, in run_step
[MFLOG|0|2025-04-21T02:20:25.002334Z|runtime|ef56e1ee-3938-479f-b4c1-d21937113a1a]    self._exec_step_function(step_func, input_obj)
[MFLOG|0|2025-04-21T02:20:25.002357Z|runtime|7dbff828-b037-4d92-b134-485e55d08157]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 64, in _exec_step_function
[MFLOG|0|2025-04-21T02:20:25.002395Z|runtime|f58a1b05-ebe2-4559-9222-604ab2fff8b3]    step_function(input_obj)
[MFLOG|0|2025-04-21T02:20:25.002418Z|runtime|7037eb9f-2b2a-400f-bf31-9a307e421056]  File "/Users/poojabaraluumesh/MSDS/spring_2/mlops/labs/lab6/classifier_train.py", line 32, in choose_model
[MFLOG|0|2025-04-21T02:20:25.002439Z|runtime|2898891d-c1b7-4b88-8935-e7db2cea1c65]    import mlflow
[MFLOG|0|2025-04-21T02:20:25.002460Z|runtime|902ec5ac-1c07-4a00-9a4b-ff4baf1d2499]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/__init__.py", line 34, in <module>
[MFLOG|0|2025-04-21T02:20:25.002483Z|runtime|32eff22d-7fdd-402f-ba64-6aa0f24655fe]    from mlflow import (
[MFLOG|0|2025-04-21T02:20:25.002505Z|runtime|7c621eb4-22db-4d81-a70e-914c22743dd8]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/data/__init__.py", line 5, in <module>
[MFLOG|0|2025-04-21T02:20:25.002525Z|runtime|55b2c6ff-1ad4-4531-b5d2-4a2302ec602e]    from mlflow.data import dataset_registry
[MFLOG|0|2025-04-21T02:20:25.002547Z|runtime|a0dae791-4a81-42ce-a40c-feb24c4d28bd]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/data/dataset_registry.py", line 138, in <module>
[MFLOG|0|2025-04-21T02:20:25.002569Z|runtime|7daae1d4-9758-46d4-9c58-03165771b0cf]    from mlflow.data.pandas_dataset import from_pandas
[MFLOG|0|2025-04-21T02:20:25.002590Z|runtime|7160937a-de6a-4024-8f43-cab73d1a46ad]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/data/pandas_dataset.py", line 6, in <module>
[MFLOG|0|2025-04-21T02:20:25.002610Z|runtime|736ea497-08a6-4196-9032-4dd583105c27]    import pandas as pd
[MFLOG|0|2025-04-21T02:20:25.002633Z|runtime|1a480026-45c5-48ca-b54b-322da4acc0d7]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pandas/__init__.py", line 26, in <module>
[MFLOG|0|2025-04-21T02:20:25.002658Z|runtime|a5a88673-78e8-4f56-b84a-3596eedee1c3]    from pandas.compat import (
[MFLOG|0|2025-04-21T02:20:25.002680Z|runtime|1a15fbde-2657-4083-85e2-1d62ec069ff2]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pandas/compat/__init__.py", line 27, in <module>
[MFLOG|0|2025-04-21T02:20:25.002702Z|runtime|273e09ff-231b-4d0a-910a-4284d6a780b6]    from pandas.compat.pyarrow import (
[MFLOG|0|2025-04-21T02:20:25.002729Z|runtime|0cde712b-995b-4252-9260-7a452ff1e510]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
[MFLOG|0|2025-04-21T02:20:25.002751Z|runtime|b757884e-1c00-40af-9e21-30319fbc5aa5]    import pyarrow as pa
[MFLOG|0|2025-04-21T02:20:25.002771Z|runtime|c2d38e13-1e9d-49aa-add3-b1468f3edca0]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pyarrow/__init__.py", line 65, in <module>
[MFLOG|0|2025-04-21T02:20:25.002794Z|runtime|209d303a-d81a-42e5-b330-d035df41be2d]    import pyarrow.lib as _lib
[MFLOG|0|2025-04-21T02:20:25.002815Z|runtime|9a21b73d-0cc8-449c-993a-bf6c24e07b61]Traceback (most recent call last):
[MFLOG|0|2025-04-21T02:20:25.002839Z|runtime|d28a967e-32ba-4739-9fca-0e926f644ce8]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
[MFLOG|0|2025-04-21T02:20:25.002860Z|runtime|26625bf2-85c0-490e-8eca-18679c9cb2cd]    raise ImportError(msg)
[MFLOG|0|2025-04-21T02:20:25.002885Z|runtime|2a63d16c-8fe1-4cae-bcd1-7a48ff6a5207]ImportError: 
[MFLOG|0|2025-04-21T02:20:25.002906Z|runtime|b767e3c0-cb63-416b-8b28-8032ea31cd44]A module that was compiled using NumPy 1.x cannot be run in
[MFLOG|0|2025-04-21T02:20:25.002927Z|runtime|6e270eaa-f0bc-4d17-92e6-140361d0db52]NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
[MFLOG|0|2025-04-21T02:20:25.002947Z|runtime|3dedaffb-d0aa-4a61-8d38-9a66da47aca3]versions of NumPy, modules must be compiled with NumPy 2.0.
[MFLOG|0|2025-04-21T02:20:25.002969Z|runtime|3db6d530-bacc-4256-8ce3-8ad988a44a4a]Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
[MFLOG|0|2025-04-21T02:20:25.002990Z|runtime|afbfb171-0162-470d-85ff-c9f7fa2d300b]
[MFLOG|0|2025-04-21T02:20:25.003011Z|runtime|a0bcf546-225b-4bdb-ab78-95baffd89d3d]If you are a user of the module, the easiest solution will be to
[MFLOG|0|2025-04-21T02:20:25.003031Z|runtime|b1a091d2-ec07-4843-8626-860922f7b828]downgrade to 'numpy<2' or try to upgrade the affected module.
[MFLOG|0|2025-04-21T02:20:25.003052Z|runtime|845bae09-a78b-474d-af0b-b0df10e4aae4]We expect that some modules will need time to support NumPy 2.
[MFLOG|0|2025-04-21T02:20:25.003073Z|runtime|f895072b-52f0-4d00-a680-68b7ec7c8a43]
[MFLOG|0|2025-04-21T02:20:25.003110Z|runtime|a2a211e1-ce4d-441d-8205-392e74639630]
[MFLOG|0|2025-04-21T02:20:25.003133Z|runtime|89323035-8759-4bd7-a312-69709b36511f]
[MFLOG|0|2025-04-21T02:20:25.853878Z|runtime|6cf93cb6-d08b-4008-924a-05e010b3fd64]A module that was compiled using NumPy 1.x cannot be run in
[MFLOG|0|2025-04-21T02:20:25.854108Z|runtime|013e73d4-b928-4d91-95be-b6acf6778041]NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
[MFLOG|0|2025-04-21T02:20:25.854161Z|runtime|4678c6d8-5e8d-4cb0-8951-ab0279747895]versions of NumPy, modules must be compiled with NumPy 2.0.
[MFLOG|0|2025-04-21T02:20:25.854198Z|runtime|87c8f691-5caf-486d-8b99-6d4bfe1c9a0b]Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
[MFLOG|0|2025-04-21T02:20:25.854233Z|runtime|3b134c1a-83ae-48da-b6de-b1c513a64230]
[MFLOG|0|2025-04-21T02:20:25.854266Z|runtime|b2a6a37b-b83a-43f6-b0ad-5053c6d569a7]If you are a user of the module, the easiest solution will be to
[MFLOG|0|2025-04-21T02:20:25.854297Z|runtime|ab6f7f4d-e072-425e-8e01-6c5e259de0bb]downgrade to 'numpy<2' or try to upgrade the affected module.
[MFLOG|0|2025-04-21T02:20:25.854326Z|runtime|3775ee1b-ee30-49c8-90a1-8d387627f87c]We expect that some modules will need time to support NumPy 2.
[MFLOG|0|2025-04-21T02:20:25.854363Z|runtime|743fceec-dfef-4b73-8756-611ce213bf94]
[MFLOG|0|2025-04-21T02:20:25.854393Z|runtime|72519cce-c95c-46f7-88da-57b316e46911]Traceback (most recent call last):  File "/Users/poojabaraluumesh/MSDS/spring_2/mlops/labs/lab6/classifier_train.py", line 54, in <module>
[MFLOG|0|2025-04-21T02:20:25.854423Z|runtime|7d4666d7-6154-4f68-9e68-3d667cbbef81]    ClassifierTrainFlow()
[MFLOG|0|2025-04-21T02:20:25.854453Z|runtime|824f4d3c-e27b-47e2-bf94-032341327664]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/flowspec.py", line 191, in __init__
[MFLOG|0|2025-04-21T02:20:25.854484Z|runtime|7b5a5059-d1fa-457f-8dd7-a7463ffdf4bf]    cli.main(self)
[MFLOG|0|2025-04-21T02:20:25.854515Z|runtime|945f98e8-7425-4cc7-86f2-80d70cf2d430]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli.py", line 619, in main
[MFLOG|0|2025-04-21T02:20:25.854600Z|runtime|4fe37cb5-2efc-49db-9e7f-761f5eaee162]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2025-04-21T02:20:25.854631Z|runtime|ded6f27e-be54-4d14-8680-01304e73df0a]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2025-04-21T02:20:25.854660Z|runtime|01f02d20-9252-4111-b838-016daa777f6b]    return self.main(*args, **kwargs)
[MFLOG|0|2025-04-21T02:20:25.854690Z|runtime|249b9e6f-9bfa-4c74-8a47-835132482520]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2025-04-21T02:20:25.854720Z|runtime|0a4a608f-8945-4367-bfa3-e0a3290ed449]    rv = self.invoke(ctx)
[MFLOG|0|2025-04-21T02:20:25.854748Z|runtime|1f3aeb17-1d69-4ea5-900b-01a42549b041]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/utils.py", line 69, in invoke
[MFLOG|0|2025-04-21T02:20:25.854776Z|runtime|70766e2b-2045-45a7-b66f-7bea9e9b5e20]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2025-04-21T02:20:25.854805Z|runtime|edfac954-f3a1-4cd2-9a5f-4801b911139e]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2025-04-21T02:20:25.854849Z|runtime|cbadf114-f89e-48e9-9b85-ca687253cd1b]    return ctx.invoke(self.callback, **ctx.params)
[MFLOG|0|2025-04-21T02:20:25.854878Z|runtime|2130a2c8-87a1-4b1d-902b-ea165cda97e8]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2025-04-21T02:20:25.854908Z|runtime|cbfd9b27-761a-4c2c-91a8-6896be721750]    return callback(*args, **kwargs)
[MFLOG|0|2025-04-21T02:20:25.854938Z|runtime|80bda7bd-88e3-412f-bb83-a321239fe7a8]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2025-04-21T02:20:25.854968Z|runtime|c7c7f80c-57eb-4749-be1c-8bbb3b66ea54]    return func(*args, **kwargs)
[MFLOG|0|2025-04-21T02:20:25.855001Z|runtime|d942756e-d20d-458b-ba43-9fac7facf19e]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2025-04-21T02:20:25.855029Z|runtime|e48a6868-1bc1-4ba9-a581-1963b08dff65]    return f(get_current_context(), *args, **kwargs)
[MFLOG|0|2025-04-21T02:20:25.855057Z|runtime|429f3688-c514-4909-bf27-5ecfba5fa48a]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/step_cmd.py", line 167, in step
[MFLOG|0|2025-04-21T02:20:25.855087Z|runtime|9b59cfd2-17e7-4595-9125-d1c1a16d7a16]    task.run_step(
[MFLOG|0|2025-04-21T02:20:25.855117Z|runtime|8a295759-10d3-4f54-a579-62ece368b486]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 670, in run_step
[MFLOG|0|2025-04-21T02:20:25.855145Z|runtime|a4c133c0-ff9b-4cb4-b03f-a07a88102bb6]    self._exec_step_function(step_func, input_obj)
[MFLOG|0|2025-04-21T02:20:25.855179Z|runtime|0aaf745f-8b3a-43d8-84f8-3ebc7b78cb08]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 64, in _exec_step_function
[MFLOG|0|2025-04-21T02:20:25.855207Z|runtime|3040e707-e31e-4a0f-a9e2-592cbe9ff0ce]    step_function(input_obj)
[MFLOG|0|2025-04-21T02:20:25.855235Z|runtime|b315eabe-7435-4d91-b340-01a8d3233a8a]  File "/Users/poojabaraluumesh/MSDS/spring_2/mlops/labs/lab6/classifier_train.py", line 32, in choose_model
[MFLOG|0|2025-04-21T02:20:25.855266Z|runtime|b114044c-355a-4686-aa00-38cbdde4c9fb]    import mlflow
[MFLOG|0|2025-04-21T02:20:25.855387Z|runtime|10665e38-61a0-484a-99e5-b09e7e9d2c73]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/__init__.py", line 34, in <module>
[MFLOG|0|2025-04-21T02:20:25.855486Z|runtime|7db30639-d507-493c-ae76-e0e0f3c1584d]    from mlflow import (
[MFLOG|0|2025-04-21T02:20:25.855533Z|runtime|618fb13e-bb34-493c-88a0-480bbf3d3559]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/data/__init__.py", line 5, in <module>
[MFLOG|0|2025-04-21T02:20:25.855571Z|runtime|f2464ca8-8387-4484-9c96-f9aca1e22322]    from mlflow.data import dataset_registry
[MFLOG|0|2025-04-21T02:20:25.855605Z|runtime|ab79265a-b1f2-440e-9b2f-1266e00d2fef]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/data/dataset_registry.py", line 138, in <module>
[MFLOG|0|2025-04-21T02:20:25.855638Z|runtime|0b16a1f8-2401-4f5c-b8ab-6854c4dd4a07]    from mlflow.data.pandas_dataset import from_pandas
[MFLOG|0|2025-04-21T02:20:25.855670Z|runtime|9ce3b386-6d60-4f89-8f8b-e199da640c42]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/data/pandas_dataset.py", line 6, in <module>
[MFLOG|0|2025-04-21T02:20:25.855701Z|runtime|c428f037-81d4-49e3-aba1-c1aed9d11837]    import pandas as pd
[MFLOG|0|2025-04-21T02:20:25.855733Z|runtime|ac3a653f-1248-461d-9f08-0509582b672a]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pandas/__init__.py", line 49, in <module>
[MFLOG|0|2025-04-21T02:20:25.855764Z|runtime|e13c55bc-fcb7-4b74-a185-bbf0a1a1436d]    from pandas.core.api import (
[MFLOG|0|2025-04-21T02:20:25.855795Z|runtime|5b55879d-401c-4b50-b473-df74b5c6bfa3]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pandas/core/api.py", line 9, in <module>
[MFLOG|0|2025-04-21T02:20:25.855824Z|runtime|f7e0751f-2808-416e-acb4-b837ddb0c739]    from pandas.core.dtypes.dtypes import (
[MFLOG|0|2025-04-21T02:20:25.855853Z|runtime|0452b769-c225-4eb0-b70b-4546a0f9ab25]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
[MFLOG|0|2025-04-21T02:20:25.855884Z|runtime|6d017331-5e76-4e45-ac1d-294098267e22]    from pandas._libs import (
[MFLOG|0|2025-04-21T02:20:25.855914Z|runtime|d2735004-3f8e-4942-851d-10f81510b11f]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pyarrow/__init__.py", line 65, in <module>
[MFLOG|0|2025-04-21T02:20:25.855943Z|runtime|3cfdd130-da7a-42bd-865c-6f98bb99b5f3]    import pyarrow.lib as _lib
[MFLOG|0|2025-04-21T02:20:25.855973Z|runtime|de92528a-ed99-4edb-bf5a-34aec6871c97]Traceback (most recent call last):
[MFLOG|0|2025-04-21T02:20:25.856002Z|runtime|0c16df46-17f1-43a9-a02f-51a488624a12]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
[MFLOG|0|2025-04-21T02:20:25.856031Z|runtime|61860186-0c5e-4535-adc8-8766f737e370]    raise ImportError(msg)
[MFLOG|0|2025-04-21T02:20:25.856061Z|runtime|57f8ba89-a155-43d9-b0b7-dca7c7814db3]ImportError: 
[MFLOG|0|2025-04-21T02:20:25.856091Z|runtime|b76fabc6-fad6-4c10-a053-3e22795c3fa2]A module that was compiled using NumPy 1.x cannot be run in
[MFLOG|0|2025-04-21T02:20:25.856120Z|runtime|78280b43-e97f-4090-b301-a9d639dc2090]NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
[MFLOG|0|2025-04-21T02:20:25.856148Z|runtime|304dcfb4-9a42-4ba1-9cb7-53d8870905e3]versions of NumPy, modules must be compiled with NumPy 2.0.
[MFLOG|0|2025-04-21T02:20:25.856178Z|runtime|e6307e24-99f5-4964-844a-8302be8ce410]Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
[MFLOG|0|2025-04-21T02:20:25.856210Z|runtime|b74321d0-9893-415a-8132-992f76c1b9d8]
[MFLOG|0|2025-04-21T02:20:25.856242Z|runtime|244344c3-532f-4e4d-b0c0-84e5eac35400]If you are a user of the module, the easiest solution will be to
[MFLOG|0|2025-04-21T02:20:25.856272Z|runtime|77e10b1c-ff28-4fb8-b927-29da79ce26ee]downgrade to 'numpy<2' or try to upgrade the affected module.
[MFLOG|0|2025-04-21T02:20:25.856301Z|runtime|c5e682ed-c296-49c7-bd42-b0f5e5306677]We expect that some modules will need time to support NumPy 2.
[MFLOG|0|2025-04-21T02:20:25.856330Z|runtime|c851886a-b136-44bf-9c90-1395d75b9891]
[MFLOG|0|2025-04-21T02:20:25.856359Z|runtime|fac6160d-7d54-4ae3-bcf9-48c5a342d65d]
[MFLOG|0|2025-04-21T02:20:25.856393Z|runtime|232312be-fa3c-428b-82cb-e07ebc9869e2]<flow ClassifierTrainFlow step choose_model> failed:
[MFLOG|0|2025-04-21T02:20:25.858690Z|runtime|01ba3624-d2c0-4b24-903d-53f11c23a706]    Internal error
[MFLOG|0|2025-04-21T02:20:25.859571Z|runtime|db1d4eac-d77d-4960-9a47-47f02b0babf6]Traceback (most recent call last):
[MFLOG|0|2025-04-21T02:20:25.859612Z|runtime|d659ae59-9b1e-4232-bd0b-ced8684bed2e]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli.py", line 619, in main
[MFLOG|0|2025-04-21T02:20:25.859643Z|runtime|a712d84c-0bea-4c64-9d5f-c2a90cfb665f]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2025-04-21T02:20:25.859674Z|runtime|152e571e-53bc-4dcb-9988-b8ef58a8822a]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2025-04-21T02:20:25.859734Z|runtime|fcb1f342-76b0-431d-b4c9-faf3b9df0953]    return self.main(args, kwargs)
[MFLOG|0|2025-04-21T02:20:26.000141Z|runtime|cee1fb02-97d1-420d-8adf-2b0af5922e77]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.000286Z|runtime|0d986fcd-094e-4f91-8105-d3a84b26859f]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2025-04-21T02:20:26.000319Z|runtime|cea2adcd-8805-4003-92c9-43c43f21a09b]    rv = self.invoke(ctx)
[MFLOG|0|2025-04-21T02:20:26.000349Z|runtime|4c0c28c9-f99d-467b-834b-f40ff892dbed]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.000371Z|runtime|6d034e5d-d329-4938-b8b3-40434b929d47]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/utils.py", line 69, in invoke
[MFLOG|0|2025-04-21T02:20:26.000392Z|runtime|62f80f03-237b-4c52-97e9-7a97b093b517]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2025-04-21T02:20:26.000413Z|runtime|89c2bbe3-9471-40c3-8420-38071139608f]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.000432Z|runtime|2b29670f-80f5-4c34-89f1-90eef79f7fcf]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2025-04-21T02:20:26.000488Z|runtime|01c0b240-0a18-4084-995d-5bcbef8dd61c]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2025-04-21T02:20:26.000545Z|runtime|92e1e46a-116c-4e17-b126-0b6a26702128]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.000578Z|runtime|58e0e24d-b7a4-4755-ae7b-d21afccd9157]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2025-04-21T02:20:26.000602Z|runtime|bf0e4b72-bf81-49af-9382-1aa0e1d47e7d]    return callback(args, kwargs)
[MFLOG|0|2025-04-21T02:20:26.000623Z|runtime|a1782104-5ebc-4306-b992-104ef804709c]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.000644Z|runtime|c162073a-40c7-4e2d-b7a1-ff12b36e398b]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2025-04-21T02:20:26.000664Z|runtime|ae860e40-816c-4081-97ee-bcd093210ed1]    return func(args, kwargs)
[MFLOG|0|2025-04-21T02:20:26.000689Z|runtime|2218ecbf-02a4-468d-9242-1b1ee060b704]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.000709Z|runtime|81dc1589-bbe9-4f28-b4f7-e609f044d54c]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2025-04-21T02:20:26.000729Z|runtime|803d2115-247a-472a-8bea-def206d467fb]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2025-04-21T02:20:26.000748Z|runtime|4e3f125d-530d-479c-b200-a0b0b3e6a81b]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.000767Z|runtime|44367699-65e4-45ed-8398-a442cf093301]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/step_cmd.py", line 167, in step
[MFLOG|0|2025-04-21T02:20:26.000786Z|runtime|099046b0-399c-4b3d-924c-2eabdb747779]    task.run_step(
[MFLOG|0|2025-04-21T02:20:26.000805Z|runtime|76ac8658-ce2e-4332-939d-fb4a22ddb9b5]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 670, in run_step
[MFLOG|0|2025-04-21T02:20:26.000825Z|runtime|715a27cb-7b98-430a-b5f1-5883551472fb]    self._exec_step_function(step_func, input_obj)
[MFLOG|0|2025-04-21T02:20:26.000844Z|runtime|06bd5e15-f419-4a37-b08f-d453b571ac93]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 64, in _exec_step_function
[MFLOG|0|2025-04-21T02:20:26.000863Z|runtime|d6cb7175-b05f-46d7-b93b-025e910de94d]    step_function(input_obj)
[MFLOG|0|2025-04-21T02:20:26.000882Z|runtime|d3ea1f07-4b75-4736-bbbf-f7741acfd36d]  File "/Users/poojabaraluumesh/MSDS/spring_2/mlops/labs/lab6/classifier_train.py", line 34, in choose_model
[MFLOG|0|2025-04-21T02:20:26.000902Z|runtime|824869fc-df93-48d1-b798-23845483b4cc]    mlflow.set_experiment('metaflow-experiment')
[MFLOG|0|2025-04-21T02:20:26.000921Z|runtime|13e78875-ac3b-40e0-9611-05bddcf13f90]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/tracking/fluent.py", line 143, in set_experiment
[MFLOG|0|2025-04-21T02:20:26.000940Z|runtime|b8d211da-9e43-48ac-8658-1927230b0853]    experiment = client.get_experiment_by_name(experiment_name)
[MFLOG|0|2025-04-21T02:20:26.000959Z|runtime|e3d0dbcd-88dc-4f74-a01c-e1aad4303794]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.000978Z|runtime|51868ae2-7ab0-4610-b1ea-3930458d1f05]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/tracking/client.py", line 1240, in get_experiment_by_name
[MFLOG|0|2025-04-21T02:20:26.000997Z|runtime|6071fa14-c54e-4760-b65a-37eb242886d1]    return self._tracking_client.get_experiment_by_name(name)
[MFLOG|0|2025-04-21T02:20:26.001016Z|runtime|c7494002-eb94-497d-95b8-9ba8268556d3]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.001035Z|runtime|80e4ecdc-db17-46fe-be85-de1b157a857d]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 484, in get_experiment_by_name
[MFLOG|0|2025-04-21T02:20:26.001054Z|runtime|881a89ca-ccd0-428e-a1fb-b9c984184941]    return self.store.get_experiment_by_name(name)
[MFLOG|0|2025-04-21T02:20:26.001073Z|runtime|ec716311-91b8-4091-be83-7a012f4ec372]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.001092Z|runtime|fe212e63-9752-40fc-9c1e-e0e05d3fcc83]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 518, in get_experiment_by_name
[MFLOG|0|2025-04-21T02:20:26.001111Z|runtime|1f589c34-1bd7-473d-b532-958aad5a7bcb]    response_proto = self._call_endpoint(GetExperimentByName, req_body)
[MFLOG|0|2025-04-21T02:20:26.001130Z|runtime|dd65a466-635a-44b2-bd49-6739e7a8f5d0]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.001149Z|runtime|a1d7b2f9-1931-4b25-97d2-84fd5c16e0d2]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 81, in _call_endpoint
[MFLOG|0|2025-04-21T02:20:26.001167Z|runtime|fa0476ae-eb54-4e39-a2d1-3c8fb49c50d2]    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
[MFLOG|0|2025-04-21T02:20:26.001186Z|runtime|7e42c8c3-4fcf-403f-a8fa-16fb663abe89]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.001205Z|runtime|fb84bf93-6f15-4b1c-aea6-4d8b6f215568]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 362, in call_endpoint
[MFLOG|0|2025-04-21T02:20:26.001224Z|runtime|68f6f03f-1bda-42c5-87fd-e6917a40a89b]    response = verify_rest_response(response, endpoint)
[MFLOG|0|2025-04-21T02:20:26.001243Z|runtime|a2002e4a-3806-4a5a-a590-9d1304b2a7b5]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-21T02:20:26.001262Z|runtime|ad9250ca-3329-4e2f-b94f-8ad6c0ff4d71]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 238, in verify_rest_response
[MFLOG|0|2025-04-21T02:20:26.001280Z|runtime|43f9558b-1abd-46a9-9aa2-85d48d5e7266]    raise MlflowException(
[MFLOG|0|2025-04-21T02:20:26.001299Z|runtime|73cd2bbc-fbf6-498a-b73e-7f941924feeb]mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/get-by-name failed with error code 404 != 200. Response body: '
[MFLOG|0|2025-04-21T02:20:26.001318Z|runtime|450435cd-f1af-49fd-b54c-9ab7f6e0c0c2]<html><head>
[MFLOG|0|2025-04-21T02:20:26.001337Z|runtime|c8ad616d-8ab9-4d56-89bc-fb12d5b63623]<meta http-equiv="content-type" content="text/html;charset=utf-8">
[MFLOG|0|2025-04-21T02:20:26.001356Z|runtime|81f881a2-011b-414d-a245-f46e85985363]<title>404 Page not found</title>
[MFLOG|0|2025-04-21T02:20:26.001374Z|runtime|8e77a0a6-35cd-477c-a7e8-c9ea1e05ccc4]</head>
[MFLOG|0|2025-04-21T02:20:26.001393Z|runtime|a013b24c-4a0b-4229-9d75-a087c2f8fbac]<body text=#000000 bgcolor=#ffffff>
[MFLOG|0|2025-04-21T02:20:26.001411Z|runtime|f9bebf51-ad1e-4dd7-b3d8-a358b9ff6b58]<h1>Error: Page not found</h1>
[MFLOG|0|2025-04-21T02:20:26.001430Z|runtime|e4f4fa19-63e7-4cb9-8eac-038324fcab7c]<h2>The requested URL was not found on this server.</h2>
[MFLOG|0|2025-04-21T02:20:26.001448Z|runtime|ed5d68f1-6ece-43f2-8636-214e163d6bcc]<h2></h2>
[MFLOG|0|2025-04-21T02:20:26.001467Z|runtime|e8c454dc-e934-48be-8e53-1775877b1bf3]</body></html>
[MFLOG|0|2025-04-21T02:20:26.001486Z|runtime|0a95a351-07ce-458d-b68e-820c6d4584a9]'
[MFLOG|0|2025-04-21T02:20:26.001508Z|runtime|9c5f07b0-b991-4b51-8e43-15c896ace26e]
[MFLOG|0|2025-04-21T02:20:26.001899Z|runtime|12e92cbc-5740-4e6e-bcda-0393597db027]Task failed.